"""HexMarket Python SDK — quantitative trading & market making."""

from hexmarket_sdk.client import HexClient
from hexmarket_sdk.auth import (
    ApiCredentials,
    build_l2_headers,
    build_order_message,
    build_auth_message,
    build_auth_token,
    build_api_key_message,
    generate_nonce,
    ed25519_sign,
    pubkey_b58,
)
from hexmarket_sdk.types import (
    Side,
    OrderType,
    TimeInForce,
    PlaceOrderParams,
    PlaceOrderResponse,
    Order,
    Trade,
    OrderBookLevel,
    OrderBook,
    MergedOrderBookLevel,
    MergedOrderBook,
    Outcome,
    Market,
    Tag,
    TagDetail,
    HexEvent,
    EventListItem,
    EventDetail,
    Position,
    UserBalance,
    VaultBalance,
    PriceSnapshot,
    TransactionResponse,
    SubmitResponse,
)

__all__ = [
    "HexClient",
    "ApiCredentials",
    "build_l2_headers",
    "build_order_message",
    "build_auth_message",
    "build_auth_token",
    "build_api_key_message",
    "generate_nonce",
    "ed25519_sign",
    "pubkey_b58",
    "Side",
    "OrderType",
    "TimeInForce",
    "PlaceOrderParams",
    "PlaceOrderResponse",
    "Order",
    "Trade",
    "OrderBookLevel",
    "OrderBook",
    "MergedOrderBookLevel",
    "MergedOrderBook",
    "Outcome",
    "Market",
    "Tag",
    "TagDetail",
    "HexEvent",
    "EventListItem",
    "EventDetail",
    "Position",
    "UserBalance",
    "VaultBalance",
    "PriceSnapshot",
    "TransactionResponse",
    "SubmitResponse",
]

__version__ = "0.1.0"
